/*CREATE A TRIGGER ON STUDENT TABLE FOR INSERT , UPDATE AND DELETE STATEMENT TODISPLAY A MESSAGE “RECORD IS AFFECTED”.*/
CREATE TRIGGER STUDENT_MSG 
ON STUDENT
AFTER INSERT,UPDATE,DELETE 
AS
BEGIN
    PRINT'RECORD AFFECTED'
END

/*CREATE A TRIGGER ON STUDENT TABLE FOR INSERT STATEMENT TO INSERT DESCRIPTION(RECORD WITH RNO=[101] IS INSERTED ON [CURRENT DATE]) IN AUDIT TABLE.*/
CREATE TRIGGER TR_STUDENT_FORINSERT 
ON STUDENT
FOR INSERT
AS    
BEGIN
    DECLARE @ID INT
    SELECT @ID= RNO FROM INSERTED
    INSERT INTO AUDIT VALUES(@ID,'RECORD WITH RNO='+CAST(@ID AS 
    VARCHAR(10))+' IS INSERTED ON '+CAST(GETDATE()AS VARCHAR(50)))
END

/*CREATE A TRIGGER ON STUDENT TABLE FOR UPDATE STATEMENT TO INSERT DESCRIPTION(RECORD WITH RNO=[101] IS UPDATED ON [CURRENT DATE]) IN AUDIT TABLE.*/
CREATE TRIGGER TR_STUDENT_FORUPDATE 
ON STUDENT
FOR UPDATE
AS    
BEGIN         
    DECLARE @ID INT
    SELECT @ID= RNO FROM INSERTED
    INSERT INTO AUDIT VALUES(@ID,'RECORD WITH RNO='+CAST(@ID AS
    VARCHAR(10))+' IS UPDATED ON'+CAST(GETDATE()AS VARCHAR(50)))
END

/*CREATE A TRIGGER ON STUDENT TABLE FOR DELETE STATEMENT TO INSERT DESCRIPTION(RECORD WITH RNO=[101] IS DELETED ON [CURRENT DATE]) IN AUDIT TABLE.*/
CREATE TRIGGER TR_STUDENT_FORDELETE 
ON STUDENT
FOR DELETE
AS    
BEGIN         
    DECLARE @ID INT
    SELECT @ID= RNO FROMDELETED
    INSERT INTO AUDIT VALUES(@ID,'RECORD WITH RNO='+CAST(@ID AS VARCHAR(10))+'IS DELETEDON'+CAST(GETDATE()AS VARCHAR(50))) 
END

/*CREATE A TRIGGER ON RESULT TABLE FOR INSERT STATEMENT TO UPDATE TOTAL MARKSAUTOMATICALLY. HERE TOTAL MARKS IS SUM OF OF SUB1,SUB2 AND SUB3.*/
CREATE TRIGGER TR_TOTALMARKS 
ON RESULT
FOR INSERT
AS
BEGIN
    DECLARE @S1 INT, @S2 INT, @S3 INT, @TOTAL INT
    SELECT @S1= SUB1 FROM INSERTED 
    SELECT @S2= SUB2 FROM INSERTED 
    SELECT @S3= SUB3 FROM INSERTED 
    SET @TOTAL= @S1+@S2+@S3
    
    UPDATE RESULT
    SET TOTAL=@TOTAL
    WHERE SUB1=@S1 AND SUB2=@S2 AND SUB3=@S3
END