CREATE TABLE STUDENT 
(
    RNO INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    BRANCH VARCHAR (50) NOT NULL
);

CREATE TABLE RESULT
(
    RNO INT NOT NULL,
    SPI DECIMAL(5,2) NOT NULL
);

INSERT INTO Student VALUES (101,'RAJU','CE') 
INSERT INTO Student VALUES (102,'AMIT','CE') 
INSERT INTO Student VALUES (103,'SANJAY','ME') 
INSERT INTO Student VALUES (104,'NEHA','EC') 
INSERT INTO Student VALUES (105,'MEERA','EE') 
INSERT INTO Student VALUES (106,'MAHESH','ME') 

INSERT INTO Result VALUES (101,8.8) 
INSERT INTO Result VALUES (102,9.2) 
INSERT INTO Result VALUES (103,7.6) 
INSERT INTO Result VALUES (104,8.2) 
INSERT INTO Result VALUES (105,7.0) 
INSERT INTO Result VALUES (105,8.9)

CREATE PROCEDURE SELECT ALL AS SELECT S.RNO, S.NAME, S.BRANCH, R.SPI FROM STUDENT S INNER JOIN RESULT R ON S.RNO = R. RNO
CREATE PROCEDURE SELECTPK @RNO INT AS SELECT S.RNO, S.NAME, S.BRANCH, R.SPI FROM STUDENT S INNER JOIN RESULT R ON S.RNO = R. RNO WHERE S.RNO = @RNO
CREATE PROCEDURE STUDENT INSERT @RNO INT, @NAME VARCHAR(50), @BRANCH VARCHAR(20) AS INSERT INTO STUDENT VALUES ( @RNO, @NAME, @BRANCH )
CREATE PROCEDURE STUDENT UPDATE @RNO INT, @BRANCH VARCHAR(20) AS UPDATE STUDENT SET BRANCH = @BRANCH WHERE RNO=@RNO
CREATE PROCEDURE STUDENT DELETE @RNO INT AS DELETE FROM STUDENT WHERE RNO = @RNO
SP_HELP DATABASE_OBJECTNAME
SP_HELPTEXT DATABASE_OBJECTNAME
SP_DEPENDS DATABASE_OBJECTNAME