CREATE TABLE STUDENT
(       
    RNO INT,       
    NAME VARCHAR(50),       
    CITY VARCHAR(50),       
    DID INT
);

CREATE TABLE ACADEMIC 
(       
    RNO INT,       
    SPI DECIMAL(4,2),       
    BKLOG INT
);

CREATE TABLE DEPARTMENT 
(
    DID INT,
    DNAME VARCHAR(50)
);

INSERT INTO STUDENT VALUES(101,'RAJU','RAJKOT',10); 
INSERT INTO STUDENT VALUES(102,'AMIT','AHMEDABAD',20); 
INSERT INTO STUDENT VALUES(103,'SANJAY','BARODA',40); 
INSERT INTO STUDENT VALUES(104,'NEHA','RAJKOT',20); 
INSERT INTO STUDENT VALUES(105,'MEERA','AHMEDABAD',30); 
INSERT INTO STUDENT VALUES(106,'MAHESH','BARODA',10); 

INSERT INTO ACADEMIC VALUES(101,8.8,0);
INSERT INTO ACADEMIC VALUES(102,9.2,2); 
INSERT INTO ACADEMIC VALUES(103,7.6,1); 
INSERT INTO ACADEMIC VALUES(104,8.2,4); 
INSERT INTO ACADEMIC VALUES(105,7.0,2); 
INSERT INTO ACADEMIC VALUES(106,8.9,3);
INSERT INTO DEPARTMENT VALUES(10,'COMPUTER'); 
INSERT INTO DEPARTMENT VALUES(20,'ELECTRICAL'); 
INSERT INTO DEPARTMENT VALUES(30,'MECHANICAL'); 
INSERT INTO DEPARTMENT VALUES(40,'CIVIL');

SELECT RNO,NAME,CITY FROM STUDENT WHERE DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER');
SELECT NAME FROM STUDENT WHERE RNO IN(SELECT RNO FROM ACADEMIC WHERE SPI>8);
SELECT RNO,NAME,CITY FROM STUDENT WHERE CITY='RAJKOT'AND DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER');
SELECT COUNT(*) FROM STUDENT WHERE DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL');
SELECT NAME FROM STUDENT WHERE RNO = (SELECT RNO FROM ACADEMIC WHERE SPI = (SELECT MAX(SPI) FROM ACADEMIC));
SELECT*FROM STUDENT WHERE RNO IN(SELECT RNO FROM ACADEMIC WHERE BKLOG>1);
SELECT * FROM STUDENT WHERE RNO = (SELECT RNO FROM ACADEMIC WHERE SPI=(SELECT MAX(SPI) FROM ACADEMIC WHERE SPI<(SELECT MAX(SPI)FROM ACADEMIC)));
/*OR
SELECT NAME FROM STUDENT WHERE RNO = (SELECT RNO FROM ACADEMIC WHERE SPI=(SELECT TOP 1 SPI FROM (SELECT DISTINCT TOP 2 SPI FROM ACADEMIC ORDER BY SPI DESC) AS TEMP ORDER BY SPI ASC));*/
SELECT NAME FROM STUDENT WHERE DID IN(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER' OR DNAME='MECHANICAL');
SELECT NAME FROM STUDENT WHERE DID=(SELECT DID FROM STUDENT WHERE RNO=102);
SELECT NAME FROM STUDENT WHERE RNO IN(SELECT RNO FROM ACADEMIC WHERE SPI>9) AND DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL');