/*WRITE A FUNCTION TO PRINT NUMBER FROM 1 TO 10*/
DECLARE @V1 INT 
SET @V1=1 
WHILE (@V1<11) 
BEGIN
PRINT @V1
SET @V1=@V1+1
END

/*WRITE A FUNCTION TO CHECK WHERE GIVING NUMBER IS ODD OR EVEN*/
DECLARE @V1 INT
SET @V1=15
BEGIN
IF @V1%2=0
PRINT'EVEN';
ELSE
PRINT'ODD';
END

/*WRITE A FUNCTION TO PRINT ODD NUMBERS BETWEEN 1 AND 10*/
DECLARE @V11 INT
SET @V1=1
WHILE(@V1<11)
BEGIN
IF @V1%2!=0
PRINT @V1;
SET @V1=@V1+1
END

/*WRITE A FUNCTION TO PRINT SUM OF NUMBERS FROM 1 TO 50*/
DECLARE @V1 INT, @SUM INT
SET @V=0
SET @SUM=0
WHILE (@V<=50)
BEGIN
    SET @SUM=@SUM+@V1
    SET @V=@V+1
END
PRINT @SUM

/*WRITE A FUNCTION TO PRINT SUM OF EVEN NUMBERS BETWEEN 1 TO 20*/
DECLARE @V INT,@SUM INT
SET @V=0
SET @SUM=0
WHILE(@V<=20)
BEGIN
IF(@V%2=0)
    SET @SUM=@SUM+@V
    SET @V=@V+1
END
PRINT @SUM

/*WRITE A FUNCTION TO CHECK WEATHER GIVEN NUMBER IS PRIME OR NOT*/
CREATE PROCEDURE PRIME
@N INT
AS
DECLARE @I INT,@FLAG INT
SET @I=2
SET @FLAG=1

WHILE(@I<=@N/2)
BEGIN 
    IF(@N%@I=0)
    BEGIN
        SET @FLAG=0
        BREAK
    END
    SET @I=@I+1
END
IF(@FLAG=1)
    PRINT'PRIME'
ELSE
    PRINT'NOT PRIME'

/*WRITE A FUNCTION TO INSERTING EVEN NUMBERS INTO EVEN TABLE & ODD NUMBEERS INTO ODD TABLE BETWEEN 1 TO 50*/
DECLARE @V1 INT
SET @V1=1
WHILE (@V1<=50)
BEGIN
IF @V1%2=0
    BEGIN
    INSERT INTO EVEN(NO)VALUES (@V1);
    END
ELSE
    BEGIN
    INSERT INTO ODD(NO)VALUES (@V1);
    END
SET @V1=@V1+1
END