CREATE TABLE STUDENT
(      
    RNO INT PRIMARY KEY,
    NAME VARCHAR(20),      
    BRANCH VARCHAR(10),      
    SPI FLOAT,
    BKLOG INT 
);

INSERT INTO STUDENT VALUES(101,'RAJU','CE',8.80,0) 
INSERT INTO STUDENT VALUES(102,'AMIT','CE',2.20,3) 
INSERT INTO STUDENT VALUES(103,'SANJAY','ME',1.50,6) 
INSERT INTO STUDENT VALUES(104,'NEHA','EC',7.65,1) 
INSERT INTO STUDENT VALUES(105,'MEERA','EE',5.52,2) 
INSERT INTO STUDENT VALUES(106,'MAHESH','EC',4.50,3)

CREATE VIEW PERSONAL AS SELECT RNO,NAME,BRANCH,SPI,BKLOG FROM STUDENT
CREATE VIEW STUDENT_DETAILS AS SELECT NAME, BRANCH,SPI FROM STUDENT
CREATE VIEW ACADEMIC AS SELECT RNO,[NAME],BRANCH FROM STUDENT
CREATE VIEW STUDENT_DATA AS SELECT RNO,NAME, BRANCH, SPI, BKLOG FROM STUDENT WHERE BKLOG > 2
CREATE VIEW STUDENT_PATTERN AS SELECT RNO, NAME, BRANCH FROM STUDENT WHERE NAME LIKE'_____'
INSERT INTO ACADEMIC VALUES(107,'MEET','ME')
UPDATE STUDENT_DETAILS SET BRANCH='ME' WHERE NAME='AMIT'
DELETE FROM ACADEMIC WHERE RNO=140