CREATE TABLE STUDENT
(
    RNO INT,
    NAME VARCHAR(20),
    BRANCH VARCHAR(10)
);

CREATE TABLE RESULT(
    RNO INT,
    SPI FLOAT 
);

CREATE TABLE EMPLOYEE (
    EMPNO VARCHAR(10), 
    NAME VARCHAR(10), 
    MANAGERNO VARCHAR(10)
);

INSERT INTO STUDENT VALUES(101,'RAJU','CE') 
INSERT INTO STUDENT VALUES(102,'AMIT','CE') 
INSERT INTO STUDENT VALUES(103,'SANJAY','ME') 
INSERT INTO STUDENT VALUES(104,'NEHA','EC') 
INSERT INTO STUDENT VALUES(105,'MEERA','EE') 
INSERT INTO STUDENT VALUES(106,'MAHESH','ME')

INSERT INTO RESULT VALUES(101,8.8) 
INSERT INTO RESULT VALUES(102,9.2) 
INSERT INTO RESULT VALUES(103,7.6) 
INSERT INTO RESULT VALUES(104,8.2) 
INSERT INTO RESULT VALUES(105,7.0) 
INSERT INTO RESULT VALUES(107,8.9)

INSERT INTO EMPLOYEE VALUES('E01','TARUN', NULL) 
INSERT INTO EMPLOYEE VALUES('E02','ROHAN','E02') 
INSERT INTO EMPLOYEE VALUES('E03','PRIYA','E01') 
INSERT INTO EMPLOYEE VALUES('E04','MILAN', 'E03') 
INSERT INTO EMPLOYEE VALUES('E05','JAY', 'E01') 
INSERT INTO EMPLOYEE VALUES('E06','ANJANA','E04')

SELECT S.RNO,NAME,BRANCH,SPI FROM STUDENT S, RESULT R
SELECT S.RNO,NAME,BRANCH,SPI FROM STUDENT S FULL OUTER JOIN RESULT R ON S.RNO=R.RNO
SELECT S.RNO,NAME,BRANCH,SPI FROM STUDENT S FULL OUTER JOIN RESULT R ON S.RNO=R.RNO   WHERE S.BRANCH='CE'
SELECT S.RNO,NAME,BRANCH,SPI FROM STUDENT S FULL OUTER JOIN RESULT R ON S.RNO=R.RNO WHERE S.BRANCH!='EC'
SELECT BRANCH,AVG(SPI) FROM STUDENT S, RESULT R WHERE S.RNO=R.RNO GROUP BY S.BRANCH
SELECT BRANCH,AVG(SPI) FROM STUDENT S, RESULT R WHERE S.RNO=R.RNO GROUP BY S.BRANCH ORDER BY AVG(SPI)
SELECT BRANCH,AVG(SPI)FROM STUDENT S, RESULT R WHERE S.RNO=R.RNO AND BRANCH IN('CE','ME') GROUP BY S.BRANCH
SELECT S.RNO,NAME,BRANCH,SPI FROM STUDENT S LEFT OUTER JOIN RESULT RON S.RNO=R.RNO
SELECT S.RNO,NAME,BRANCH,SPI FROM STUDENT S RIGHT OUTER JOIN RESULT RON S.RNO=R.RNO
SELECT S.RNO,NAME,BRANCH,SPI FROM STUDENT S FULL OUTER JOIN RESULT RON S.RNO=R.RNO
SELECT EMP.NAME,MNGR.NAME FROM EMPLOYEE EMP,EMPLOYEE MNGR WHERE EMP.MANAGERNO=MNGR.EMPLOYEENO