CREATE TABLE STUDENT 
(
    RNO INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    BRANCH VARCHAR (50) NOT NULL
);

CREATE TABLE RESULT
(
    RNO INT NOT NULL,
    SPI DECIMAL(5,2) NOT NULL
);

INSERT INTO Student VALUES (101,'RAJU','CE') 
INSERT INTO Student VALUES (102,'AMIT','CE') 
INSERT INTO Student VALUES (103,'SANJAY','ME') 
INSERT INTO Student VALUES (104,'NEHA','EC') 
INSERT INTO Student VALUES (105,'MEERA','EE') 
INSERT INTO Student VALUES (106,'MAHESH','ME') 

INSERT INTO Result VALUES (101,8.8) 
INSERT INTO Result VALUES (102,9.2) 
INSERT INTO Result VALUES (103,7.6) 
INSERT INTO Result VALUES (104,8.2) 
INSERT INTO Result VALUES (105,7.0) 
INSERT INTO Result VALUES (105,8.9)

CREATE PROCEDURE SELECT ALL AS SELECT S.RNO, S.NAME, S.BRANCH, R.SPI FROM STUDENT S INNER JOIN RESULT R ON S.RNO = R. RNO
