CREATE TABLE EMPLOYEE (
    EID INT,
    ENAME VARCHAR(10), 
    DEPARTMENT VARCHAR(10), 
    SALARY INT,
    JOININGDATE DATETIME, 
    CITY VARCHAR(10)
);

INSERT INTO EMPLOYEE VALUES(101,'RAHUL','ADMIN',56000,'1-JAN-90','RAJKOT') 
INSERT INTO EMPLOYEE VALUES(102,'HARDIK','IT',18000,'25-SEP-90','AHMEDABAD') 
INSERT INTO EMPLOYEE VALUES(103,'BHAVIN','HR',25000,'14-MAY-91','BARODA') 
INSERT INTO EMPLOYEE VALUES(104,'BHOOMI','ADMIN',39000,'8-FEB-91','RAJKOT') 
INSERT INTO EMPLOYEE VALUES(105,'ROHIT','IT',17000,'23-JUL-90','JAMNAGAR') 
INSERT INTO EMPLOYEE VALUES(106,'PRIYA','IT',9000,'18-OCT-90','AHMEDABAD') 
INSERT INTO EMPLOYEE VALUES(107,'NEHA','HR',34000,'25-DEC-91','RAJKOT')

SELECT MAX(SALARY)AS MAXIMUM,MIN(SALARY)AS MINIMUM, SUM(SALARY)AS TOTAL_SAL,AVG(SALARY)AS AVERAGE_SAL FROM EMPLOYEE
SELECT COUNT(ENAME) "TOTAL NO OF EMPLOYEE" FROM EMPLOYEE
SELECT MAX(SALARY)AS MAXIMUM FROM EMPLOYEE WHERE DEPARTMENT='IT'
SELECT COUNT(DISTINCT CITY) "TOTAL CITY" FROM EMPLOYEE
SELECT CITY,COUNT(ENAME)FROM EMPLOYEE GROUP BY CITY
SELECT CITY,COUNT(ENAME)FROM EMPLOYEE GROUP BY CITY HAVING COUNT(ENAME)>1
SELECT DEPARTMENT,SUM(SALARY)FROM EMPLOYEE GROUP BY DEPARTMENT
SELECT AVG(SALARY)FROM EMPLOYEE GROUP BY DEPARTMENT
SELECT MIN(SALARY)FROM EMPLOYEE WHERE CITY='AHMEDABAD'
SELECT DEPARTMENT,SUM(SALARY)FROM EMPLOYEE WHERE CITY='RAJKOT'GROUP BY DEPARTMENT HAVING SUM(SALARY)>50000
SELECT COUNT(ENAME)FROM EMPLOYEE WHERE CITY='RAJKOT'
SELECT MAX(SALARY)-MIN(SALARY) "DIFFERENCE" FROM EMPLOYEE
SELECT COUNT(ENAME)FROM EMPLOYEE WHERE JOININGDATE<'1/JAN/91'
SELECT DEPARTMENT,SUM(SALARY)FROM EMPLOYEE GROUP BY DEPARTMENT HAVING SUM(SALARY)>35000 ORDER BY SUM(SALARY)
SELECT DEPARTMENT FROM EMPLOYEE GROUP BY DEPARTMENT HAVING COUNT(ENAME)>2