CREATE TABLE STUDENT
(
    STUID int,
    FIRSTNAME varchar(25),
    LASTNAME varchar(25),
    WEBSITE varchar(50),
    CITY VARCHAR(25)
);

INSERT INTO STUDENT
VALUES(1011, 'KEYUR', 'PATEL', 'techonthenet.com', 'RAJKOT'),
      (1022, 'HARDIK', 'SHAH', 'digminecraft.com', 'AHMEDABAD'),
	  (1033, 'KAJAL', 'TRIVADI', 'bigactivities.com', 'BARODA'),
	  (1044, 'BHOOMI', 'GAJERA', 'checkyoumath.com', 'AHMEDABAD'),
	  (1055, 'HARMIT', 'MITEL', NULL, 'RAJKOT'),
	  (1066, 'ASHOK', 'JANI', NULL, 'BARODA');

SELECT FIRSTNAME FROM STUDENT WHERE NAME LIKE 'K%';
SELECT FIRSTNAME FROM STUDENT WHERE NAME LIKE '_____';
SELECT FIRSTNAME,LASTNAME FROM STUDENT WHERE CITY LIKE '_____A';
SELECT * FROM STUDENT WHERE LASTNAME LIKE '%TEL';
SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'HA%T';
SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'K_Y%';
SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE IS NULL AND NAME LIKE '_____';
SELECT * FROM STUDENT WHERE LASTNAME LIKE '%JER%';
SELECT * FROM STUDENT WHERE CITY LIKE '[R,B]%';
SELECT * FROM STUDENT WHERE WEBSITE IS NOT NULL;
SELECT * FROM STUDENT WHERE FIRSTNAME LIKE '[A-H]%';
SELECT * FROM STUDENT WHERE FIRSTNAME LIKE '_[A,E,I,O,U]%';