CREATE TABLE CRICKET(
    NAME VARCHAR(20),
    CITY VARCHAR(20),
    AGE INT
);

INSERT INTO CRICKET VALUES('SACHIN TENDULKAR','MUMBAI',30) 
INSERT INTO CRICKET VALUES('RAHUL DRAVID','BOMBAY',35) 
INSERT INTO CRICKET VALUES('M. S. DHONI','JHARKHAND',31) 
INSERT INTO CRICKET VALUES('SURESH RAINA','GUJARAT',30)

SELECT*INTO WORLDCUP FROM CRICKET
SELECT NAME,CITYINTO T20 FROM CRICKET
SELECT*INTO IPL FROM CRICKET WHERE 1=2
INSERT INTO IPL SELECT*FROM CRICKET WHERENAMELIKE'_A_____%'
DELETE FROM IPL
DELETE FROM CRICKET WHERE CITY='JHARKHAND'
SP_RENAME 'IPL','IPL2018'
DROP TABLE T20
